### ISSUE TITLE
jsonld extension support in urls

### ISSUE THREAD

**Issue by satra** [schemaorg/sdopythonapp#12]
it seems that schema.org has stopped supporting the adding of jsonld extension. so this https://schema.org/Person.jsonld used to work just a few days back and now returns a 404.

is that by design?

**Comment by RichardWallis** [comment]
Hi @satra 

Support for that feature was dropped as part of the reengineering undertaken in response to the significant DOS attack the site suffered recently.

We have moved to a totally static site, which does not support content negotiation, and therefore support for this always experimental feature.

**Comment by satra** [comment]
thank you @RichardWallis - that's a bummer.

could static content be supported? i.e. have url.jsonld and url.ttl as http retrievable information? 

it was super handy to be able to look at the schema underneath at times.

**Comment by RichardWallis** [comment]
You can always download dumps of all terms from the [developers page](https://schema.org/docs/developers.html#defs)  which is in the process of being updated to reflect this change.

**Comment by danbri** [comment]
Yeah, if there were a lot of demand for per-page machine formats we could revisit this, but since our definitions only really make sense as a network of interdependent term definitions, I'd strongly encourage you to look at the developers page formats. If the big downloads are intimidating, you can also load them into SPARQL graph databases, e.g. see https://dydra.com/danbri/schema-org-v7-04 for a recent release plus a few sample queries.

**Comment by satra** [comment]
thanks @danbri - it was more of a convenience rather than how we use it. i often use that form during meetings/talks. we are also running a different server that's modeled on schema.org type behavior, hence a bit of the surprise. https://schema.repronim.org/rl/

i'm fine with the decision, just didn't know if it was a service malfunction or intent, hence this issue.

**Comment by danbri** [comment]
Thanks, sorry for the lack of notice - we moved quickly due to the DOS
